
--REMOVE USELESS SCHEMAS

CREATE USER cas IDENTIFIED BY cas 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";


-- QUOTAS
ALTER USER cas QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO cas WITH ADMIN OPTION;
GRANT "DBA" TO cas WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO cas WITH ADMIN OPTION;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO cas WITH ADMIN OPTION;
GRANT "CTXAPP" TO cas WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO cas WITH ADMIN OPTION;
GRANT "CONNECT" TO cas WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO cas WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO cas WITH ADMIN OPTION;
GRANT "APEX_ADMINISTRATOR_ROLE" TO cas WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO cas WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO cas WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO cas WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO cas WITH ADMIN OPTION;
GRANT "DBFS_ROLE" TO cas WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO cas WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO cas WITH ADMIN OPTION;
GRANT "PLUSTRACE" TO cas WITH ADMIN OPTION;
GRANT "RESOURCE" TO cas WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO cas WITH ADMIN OPTION;
GRANT "DELETE_CATALOG_ROLE" TO cas WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO cas WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES" TO cas WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO cas WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO cas WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO cas WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO cas WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO cas WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO cas WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO cas WITH ADMIN OPTION;
GRANT "XDBADMIN" TO cas WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO cas WITH ADMIN OPTION;
ALTER USER cas DEFAULT ROLE "DATAPUMP_EXP_FULL_DATABASE","DBA","HS_ADMIN_EXECUTE_ROLE","ADM_PARALLEL_EXECUTE_TASK","CTXAPP","SELECT_CATALOG_ROLE","CONNECT","DATAPUMP_IMP_FULL_DATABASE","OEM_MONITOR","APEX_ADMINISTRATOR_ROLE","AQ_USER_ROLE","SCHEDULER_ADMIN","XDB_SET_INVOKER","RECOVERY_CATALOG_OWNER","DBFS_ROLE","XDB_WEBSERVICES_OVER_HTTP","HS_ADMIN_SELECT_ROLE","PLUSTRACE","RESOURCE","AQ_ADMINISTRATOR_ROLE","DELETE_CATALOG_ROLE","XDB_WEBSERVICES_WITH_PUBLIC","XDB_WEBSERVICES","EXECUTE_CATALOG_ROLE","EXP_FULL_DATABASE","GATHER_SYSTEM_STATISTICS","LOGSTDBY_ADMINISTRATOR","AUTHENTICATEDUSER","OEM_ADVISOR","HS_ADMIN_ROLE","XDBADMIN","IMP_FULL_DATABASE";

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO cas WITH ADMIN OPTION;
GRANT DROP ANY CONTEXT TO cas WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE TO cas WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO cas WITH ADMIN OPTION;
GRANT MANAGE ANY FILE GROUP TO cas WITH ADMIN OPTION;
GRANT ALTER PUBLIC DATABASE LINK TO cas WITH ADMIN OPTION;
GRANT MANAGE FILE GROUP TO cas WITH ADMIN OPTION;
GRANT ALTER ANY INDEX TO cas WITH ADMIN OPTION;
GRANT DROP ANY SEQUENCE TO cas WITH ADMIN OPTION;
GRANT ALTER PROFILE TO cas WITH ADMIN OPTION;
GRANT UNDER ANY TABLE TO cas WITH ADMIN OPTION;
GRANT CREATE ASSEMBLY TO cas WITH ADMIN OPTION;
GRANT DROP ANY LIBRARY TO cas WITH ADMIN OPTION;
GRANT ALTER ANY EDITION TO cas WITH ADMIN OPTION;
GRANT CREATE ROLE TO cas WITH ADMIN OPTION;
GRANT CREATE LIBRARY TO cas WITH ADMIN OPTION;
GRANT DROP ROLLBACK SEGMENT TO cas WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO cas WITH ADMIN OPTION;
GRANT ALTER ANY PROCEDURE TO cas WITH ADMIN OPTION;
GRANT ADMINISTER DATABASE TRIGGER TO cas WITH ADMIN OPTION;
GRANT DROP ANY MEASURE FOLDER TO cas WITH ADMIN OPTION;
GRANT CREATE ANY PROCEDURE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY OUTLINE TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY INDEXTYPE TO cas WITH ADMIN OPTION;
GRANT CREATE ANY DIRECTORY TO cas WITH ADMIN OPTION;
GRANT ALTER ANY RULE SET TO cas WITH ADMIN OPTION;
GRANT ALTER ANY MINING MODEL TO cas WITH ADMIN OPTION;
GRANT DEBUG CONNECT SESSION TO cas WITH ADMIN OPTION;
GRANT CREATE ANY MINING MODEL TO cas WITH ADMIN OPTION;
GRANT ALTER SESSION TO cas WITH ADMIN OPTION;
GRANT CREATE MATERIALIZED VIEW TO cas WITH ADMIN OPTION;
GRANT MERGE ANY VIEW TO cas WITH ADMIN OPTION;
GRANT CREATE ANY INDEX TO cas WITH ADMIN OPTION;
GRANT CREATE DIMENSION TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE SET TO cas WITH ADMIN OPTION;
GRANT ALTER ANY MATERIALIZED VIEW TO cas WITH ADMIN OPTION;
GRANT AUDIT SYSTEM TO cas WITH ADMIN OPTION;
GRANT CREATE OPERATOR TO cas WITH ADMIN OPTION;
GRANT MANAGE ANY QUEUE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY SQL PROFILE TO cas WITH ADMIN OPTION;
GRANT GRANT ANY OBJECT PRIVILEGE TO cas WITH ADMIN OPTION;
GRANT CREATE INDEXTYPE TO cas WITH ADMIN OPTION;
GRANT AUDIT ANY TO cas WITH ADMIN OPTION;
GRANT DEBUG ANY PROCEDURE TO cas WITH ADMIN OPTION;
GRANT CREATE ANY MEASURE FOLDER TO cas WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO cas WITH ADMIN OPTION;
GRANT CREATE MEASURE FOLDER TO cas WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE BUILD PROCESS TO cas WITH ADMIN OPTION;
GRANT CREATE VIEW TO cas WITH ADMIN OPTION;
GRANT ALTER DATABASE LINK TO cas WITH ADMIN OPTION;
GRANT ALTER ANY ASSEMBLY TO cas WITH ADMIN OPTION;
GRANT CREATE ANY EVALUATION CONTEXT TO cas WITH ADMIN OPTION;
GRANT SELECT ANY MINING MODEL TO cas WITH ADMIN OPTION;
GRANT DELETE ANY CUBE DIMENSION TO cas WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO cas WITH ADMIN OPTION;
GRANT CREATE SESSION TO cas WITH ADMIN OPTION;
GRANT CREATE RULE TO cas WITH ADMIN OPTION;
GRANT BECOME USER TO cas WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO cas WITH ADMIN OPTION;
GRANT INSERT ANY MEASURE FOLDER TO cas WITH ADMIN OPTION;
GRANT CREATE ANY SQL PROFILE TO cas WITH ADMIN OPTION;
GRANT FORCE ANY TRANSACTION TO cas WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY SEQUENCE TO cas WITH ADMIN OPTION;
GRANT SELECT ANY CUBE DIMENSION TO cas WITH ADMIN OPTION;
GRANT CREATE ANY EDITION TO cas WITH ADMIN OPTION;
GRANT CREATE EXTERNAL JOB TO cas WITH ADMIN OPTION;
GRANT DROP ANY MATERIALIZED VIEW TO cas WITH ADMIN OPTION;
GRANT CREATE ANY CUBE BUILD PROCESS TO cas WITH ADMIN OPTION;
GRANT FLASHBACK ANY TABLE TO cas WITH ADMIN OPTION;
GRANT DROP ANY RULE SET TO cas WITH ADMIN OPTION;
GRANT BACKUP ANY TABLE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY CUBE TO cas WITH ADMIN OPTION;
GRANT CREATE TABLE TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY LIBRARY TO cas WITH ADMIN OPTION;
GRANT DROP ANY OUTLINE TO cas WITH ADMIN OPTION;
GRANT EXECUTE ASSEMBLY TO cas WITH ADMIN OPTION;
GRANT CREATE ANY DIMENSION TO cas WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY CLUSTER TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY CLASS TO cas WITH ADMIN OPTION;
GRANT DROP ANY DIMENSION TO cas WITH ADMIN OPTION;
GRANT CREATE ANY RULE SET TO cas WITH ADMIN OPTION;
GRANT SELECT ANY SEQUENCE TO cas WITH ADMIN OPTION;
GRANT UNDER ANY TYPE TO cas WITH ADMIN OPTION;
GRANT MANAGE TABLESPACE TO cas WITH ADMIN OPTION;
GRANT DROP ANY OPERATOR TO cas WITH ADMIN OPTION;
GRANT CREATE ANY OPERATOR TO cas WITH ADMIN OPTION;
GRANT EXEMPT IDENTITY POLICY TO cas WITH ADMIN OPTION;
GRANT CREATE TYPE TO cas WITH ADMIN OPTION;
GRANT CREATE TABLESPACE TO cas WITH ADMIN OPTION;
GRANT SELECT ANY TRANSACTION TO cas WITH ADMIN OPTION;
GRANT DELETE ANY MEASURE FOLDER TO cas WITH ADMIN OPTION;
GRANT CREATE ANY CUBE TO cas WITH ADMIN OPTION;
GRANT LOCK ANY TABLE TO cas WITH ADMIN OPTION;
GRANT CREATE EVALUATION CONTEXT TO cas WITH ADMIN OPTION;
GRANT DROP ANY TYPE TO cas WITH ADMIN OPTION;
GRANT ADVISOR TO cas WITH ADMIN OPTION;
GRANT CREATE PUBLIC DATABASE LINK TO cas WITH ADMIN OPTION;
GRANT ANALYZE ANY TO cas WITH ADMIN OPTION;
GRANT DROP ANY RULE TO cas WITH ADMIN OPTION;
GRANT INSERT ANY CUBE DIMENSION TO cas WITH ADMIN OPTION;
GRANT CREATE ROLLBACK SEGMENT TO cas WITH ADMIN OPTION;
GRANT CREATE ANY JOB TO cas WITH ADMIN OPTION;
GRANT ALTER USER TO cas WITH ADMIN OPTION;
GRANT QUERY REWRITE TO cas WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO cas WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO cas WITH ADMIN OPTION;
GRANT GLOBAL QUERY REWRITE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY CUBE DIMENSION TO cas WITH ADMIN OPTION;
GRANT CREATE ANY CUBE DIMENSION TO cas WITH ADMIN OPTION;
GRANT DROP ANY CLUSTER TO cas WITH ADMIN OPTION;
GRANT CREATE ANY RULE TO cas WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE DIMENSION TO cas WITH ADMIN OPTION;
GRANT SYSDBA TO cas WITH ADMIN OPTION;
GRANT ADMINISTER RESOURCE MANAGER TO cas WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO cas WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO cas WITH ADMIN OPTION;
GRANT DROP ANY MINING MODEL TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO cas WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY PROGRAM TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY TYPE TO cas WITH ADMIN OPTION;
GRANT ON COMMIT REFRESH TO cas WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO cas WITH ADMIN OPTION;
GRANT COMMENT ANY MINING MODEL TO cas WITH ADMIN OPTION;
GRANT ADMINISTER SQL TUNING SET TO cas WITH ADMIN OPTION;
GRANT SYSOPER TO cas WITH ADMIN OPTION;
GRANT CREATE ANY INDEXTYPE TO cas WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO cas WITH ADMIN OPTION;
GRANT RESTRICTED SESSION TO cas WITH ADMIN OPTION;
GRANT DEQUEUE ANY QUEUE TO cas WITH ADMIN OPTION;
GRANT ANALYZE ANY DICTIONARY TO cas WITH ADMIN OPTION;
GRANT ALTER ANY INDEXTYPE TO cas WITH ADMIN OPTION;
GRANT ADMINISTER ANY SQL TUNING SET TO cas WITH ADMIN OPTION;
GRANT CREATE USER TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY OPERATOR TO cas WITH ADMIN OPTION;
GRANT CREATE CUBE BUILD PROCESS TO cas WITH ADMIN OPTION;
GRANT CREATE PROFILE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO cas WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY LIBRARY TO cas WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO cas WITH ADMIN OPTION;
GRANT CREATE ANY CLUSTER TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE TO cas WITH ADMIN OPTION;
GRANT ALTER TABLESPACE TO cas WITH ADMIN OPTION;
GRANT UNDER ANY VIEW TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY ASSEMBLY TO cas WITH ADMIN OPTION;
GRANT GRANT ANY PRIVILEGE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO cas WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO cas WITH ADMIN OPTION;
GRANT EXPORT FULL DATABASE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY EVALUATION CONTEXT TO cas WITH ADMIN OPTION;
GRANT FLASHBACK ARCHIVE ADMINISTER TO cas WITH ADMIN OPTION;
GRANT IMPORT FULL DATABASE TO cas WITH ADMIN OPTION;
GRANT CREATE ANY OUTLINE TO cas WITH ADMIN OPTION;
GRANT COMMENT ANY TABLE TO cas WITH ADMIN OPTION;
GRANT CREATE DATABASE LINK TO cas WITH ADMIN OPTION;
GRANT DROP PUBLIC SYNONYM TO cas WITH ADMIN OPTION;
GRANT DROP USER TO cas WITH ADMIN OPTION;
GRANT CHANGE NOTIFICATION TO cas WITH ADMIN OPTION;
GRANT CREATE MINING MODEL TO cas WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO cas WITH ADMIN OPTION;
GRANT DROP PROFILE TO cas WITH ADMIN OPTION;
GRANT CREATE ANY MATERIALIZED VIEW TO cas WITH ADMIN OPTION;
GRANT CREATE RULE SET TO cas WITH ADMIN OPTION;
GRANT EXEMPT ACCESS POLICY TO cas WITH ADMIN OPTION;
GRANT MANAGE SCHEDULER TO cas WITH ADMIN OPTION;
GRANT READ ANY FILE GROUP TO cas WITH ADMIN OPTION;
GRANT FORCE TRANSACTION TO cas WITH ADMIN OPTION;
GRANT DROP ANY CUBE BUILD PROCESS TO cas WITH ADMIN OPTION;
GRANT ALTER ANY TYPE TO cas WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO cas WITH ADMIN OPTION;
GRANT DROP PUBLIC DATABASE LINK TO cas WITH ADMIN OPTION;
GRANT DROP ANY INDEXTYPE TO cas WITH ADMIN OPTION;
GRANT DROP ANY SQL PROFILE TO cas WITH ADMIN OPTION;
GRANT ALTER SYSTEM TO cas WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO cas WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY DIMENSION TO cas WITH ADMIN OPTION;
GRANT DROP ANY CUBE DIMENSION TO cas WITH ADMIN OPTION;
GRANT DROP ANY CUBE TO cas WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO cas WITH ADMIN OPTION;
GRANT DROP ANY ASSEMBLY TO cas WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO cas WITH ADMIN OPTION;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO cas WITH ADMIN OPTION;
GRANT DROP ANY DIRECTORY TO cas WITH ADMIN OPTION;
GRANT ENQUEUE ANY QUEUE TO cas WITH ADMIN OPTION;
GRANT DROP ANY EVALUATION CONTEXT TO cas WITH ADMIN OPTION;
GRANT CREATE ANY ASSEMBLY TO cas WITH ADMIN OPTION;
GRANT CREATE ANY TYPE TO cas WITH ADMIN OPTION;
GRANT CREATE CLUSTER TO cas WITH ADMIN OPTION;
GRANT CREATE ANY CONTEXT TO cas WITH ADMIN OPTION;
GRANT EXECUTE ANY EVALUATION CONTEXT TO cas WITH ADMIN OPTION;
GRANT RESUMABLE TO cas WITH ADMIN OPTION;
GRANT CREATE ANY LIBRARY TO cas WITH ADMIN OPTION;
GRANT DROP ANY EDITION TO cas WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO cas WITH ADMIN OPTION;
GRANT ALTER DATABASE TO cas WITH ADMIN OPTION;
GRANT SELECT ANY CUBE TO cas WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO cas WITH ADMIN OPTION;
GRANT ALTER ANY RULE TO cas WITH ADMIN OPTION;
GRANT CREATE CUBE DIMENSION TO cas WITH ADMIN OPTION;
GRANT ALTER ANY OPERATOR TO cas WITH ADMIN OPTION;
GRANT CREATE CUBE TO cas WITH ADMIN OPTION;
GRANT ALTER RESOURCE COST TO cas WITH ADMIN OPTION;
GRANT DROP TABLESPACE TO cas WITH ADMIN OPTION;
GRANT ALTER ROLLBACK SEGMENT TO cas WITH ADMIN OPTION;

--REMOVE USELESS SCHEMAS
DROP USER MDSYS CASCADE;
DROP USER OUTLN CASCADE;
DROP USER HR CASCADE;
DROP USER CTXSYS CASCADE;
DROP USER ANONYMOUS CASCADE;
DROP USER APEX_PUBLIC_USER CASCADE;
--DROP USER FLOW_FILES CASCADE;
--DROP USER APEX_040000 CASCADE;


--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "CAS"."USER" 
   (	"ID" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into "CAS"."USER"
SET DEFINE OFF;

Insert into "CAS"."USER" (ID,USERNAME,PASSWORD) values ('id','ignatius','password');
-
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAS"."USER_PK" ON "CAS"."USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER
--------------------------------------------------------

  ALTER TABLE "CAS"."USER" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CAS"."USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "CAS"."USER" MODIFY ("PASSWORD" NOT NULL ENABLE);

  


  




