# Pull base image
# ---------------
FROM wnameless/oracle-xe-11g

# Maintainer
# ----------
MAINTAINER Arquitectura DIA <dia.es.arquitectura.soft@diagroup.com>



ADD /sql/ /docker-entrypoint-initdb.d/