FROM redis:3.0

# Maintainer
# ----------
MAINTAINER Arquitectura DIA <dia.es.arquitectura.soft@diagroup.com>

COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]